package com.wunderground.weatherunderground.wuapi;

/**
 * Created by Anton Azaryan on 04.06.2017.
 */

public interface WUCurrentConditions {

    int WC_DRIZZLE = 0XEC00;
    int WC_RAIN = 0XEC01;
    int WC_SNOW = 0XEC02;
    int WC_SNOW_GRAINS = 0XEC03;
    int WC_ICE_CRYSTALS = 0XEC04;
    int WC_ICE_PELLETS = 0XEC05;
    int WC_HAIL = 0XEC06;
    int WC_MIST = 0XEC07;
    int WC_FOG = 0XEC08;
    int WC_FOG_PATCHES = 0XEC09;
    int WC_SMOKE = 0XEC10;
    int WC_VOLCANIC_ASH = 0XEC11;
    int WC_WIDESPREAD_DUST = 0XEC12;
    int WC_SAND = 0XEC13;
    int WC_HAZE = 0XEC14;
    int WC_SPRAY = 0XEC15;
    int WC_DUST_WHIRLS = 0XEC16;
    int WC_SANDSTORM = 0XEC17;
    int WC_LOW_DRIFTING_SNOW = 0XEC18;
    int WC_LOW_DRIFTING_WIDESPREAD_DUST = 0XEC19;
    int WC_LOW_DRIFTING_SAND = 0XEC20;
    int WC_BLOWING_SNOW = 0XEC21;
    int WC_BLOWING_WIDESPREAD_DUST = 0XEC22;
    int WC_BLOWING_SAND = 0XEC23;
    int WC_RAIN_MIST = 0XEC24;
    int WC_RAIN_SHOWERS = 0XEC25;
    int WC_SNOW_SHOWERS = 0XEC26;
    int WC_SNOW_BLOWING_SNOW_MIST = 0XEC27;
    int WC_ICE_PELLET_SHOWERS = 0XEC28;
    int WC_HAIL_SHOWERS = 0XEC29;
    int WC_SMALL_HAIL_SHOWERS = 0XEC30;
    int WC_THUNDERSTORM = 0XEC31;
    int WC_THUNDERSTORMS_AND_RAIN = 0XEC32;
    int WC_THUNDERSTORMS_AND_SNOW = 0XEC33;
    int WC_THUNDERSTORMS_AND_ICE_PELLETS = 0XEC34;
    int WC_THUNDERSTORMS_WITH_HAIL = 0XEC35;
    int WC_THUNDERSTORMS_WITH_SMALL_HAIL = 0XEC36;
    int WC_FREEZING_DRIZZLE = 0XEC37;
    int WC_FREEZING_RAIN = 0XEC38;
    int WC_FREEZING_FOG = 0XEC39;
    int WC_PATCHES_OF_FOG = 0XEC40;
    int WC_SHALLOW_FOG = 0XEC41;
    int WC_PARTIAL_FOG = 0XEC42;
    int WC_OVERCAST = 0XEC43;
    int WC_CLEAR = 0XEC44;
    int WC_PARTLY_CLOUDY = 0XEC45;
    int WC_MOSTLY_CLOUDY = 0XEC46;
    int WC_SCATTERED_CLOUDS = 0XEC47;
    int WC_SMALL_HAIL = 0XEC48;
    int WC_SQUALLS = 0XEC49;
    int WC_FUNNEL_CLOUD = 0XEC50;
    int WC_UNKNOWN_PRECIPITATION = 0XEC51;
    int WC_UNKNOWN = 0XEC52;

}
